version: "3.5"

services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
    networks:
        - inception
  # mariadb:
  #   build: ./mariadb
  #   image: mariadb
  #   ports:
  #       - "3306:3306"
  #   networks:
  #       - inception
  # volume:
  wordpress:
    build: ./wordpress
    image: wordpress
    ports:
        - "9000:9000"
    networks:
        - inception
    # volume:
networks:
  inception:
    driver: bridge
