version: "3.5"

services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
    networks:
        - inception
  # mariadb:
  #   build: ./mariadb
  #   image: mariadb
  # expose:
  #     - "3306"
  #   networks:
  #       - inception
  # volume:
  wordpress:
    build: ./wordpress
    image: wordpress
    expose:
      - "9000"
    networks:
        - inception
    # volume:
networks:
  inception:
    driver: bridge
