version: '3'
services:
  mysql:
    env_file:
     - .env
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --host=localhost --password="${DB_ROOT_PWD}"
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
    restart: always
    networks:
        - inception
  wordpress:
    env_file:
     - .env
    depends_on:
      mysql:
        condition: service_healthy
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    restart: always
    networks:
        - inception
  nginx:
    build: requirements/nginx
    image: nginx
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_volume:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
        - inception
networks:
  inception:
    driver: bridge
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/ereali/data/wordpress_volume
      type: volume
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/ereali/data/mariadb_volume
      o: bind