version: "3.5"

services:
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "443:443"
    mariadb:
        build: ./mariadb
        image: mariadb
        ports:
            - "3306:3306"
