version: '3'
services:
  mysql:
    env_file:
     - .env
    build: requirements/mariadb
    # image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    networks:
        - inception
  wordpress:
    env_file:
     - .env
    depends_on:
      - mysql
    build: requirements/wordpress
    image: wordpress
    # image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
        - inception
  nginx:
    build: requirements/nginx
    image: nginx
    volumes:
      - ./requirements/nginx:/etc/nginx/conf.d
      - wordpress_volume:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
        - inception
networks:
  inception:
    driver: bridge
volumes:
  wordpress_volume:
    driver: local
    # name: wordpress_volume
    driver_opts:
      device: /home/lara/data/wordpress_volume
      type: volume
      o: bind
  mariadb_volume:
    driver: local
    # name: mariadb_volume
    driver_opts:
      device: /home/lara/data/mariadb_volume
      type: volume
      o: bind

# environment:
  # WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
  # MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  # WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
  # WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
  # WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
  # WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
# environment:
#   MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#   MYSQL_DATABASE=${MYSQL_DATABASE}
#   MYSQL_USER=${MYSQL_USER}
#   MYSQL_PASSWORD=${MYSQL_PASSWORD}